(() => {
  'use strict';
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=960,H=540,ground=480;
  const files=['sky.png','desert-bg.png','desert-tile.png','desert-top.png','island.png','oniku10.png','oniku11.png','oniku12.png','oniku13.png','oniku6.png','kabu.png','stock.png','tori.png','shitake.png','uributa.png','result-bg.png','sumomo.png','shika.png','shitake3.png','neko.png','himeniku.png','kani.png','miia.png','zarigani.png'];
  const img=Object.fromEntries(files.map(n=>{const i=new Image();i.src=n;return[n,i]}));
  const audio={stage:document.querySelector('#stage-bgm'),result:document.querySelector('#result-bgm'),jump:document.querySelector('#jump-sound'),coin:document.querySelector('#coin-sound'),dead:document.querySelector('#dead-sound'),hit:document.querySelector('#hit-sound')};
  const resultPanel=document.querySelector('#result-panel'),resultScore=document.querySelector('#result-score'),resultBest=document.querySelector('#result-best'),scoreStatus=document.querySelector('#score-status'),scoreForm=document.querySelector('#score-form'),playerName=document.querySelector('#player-name');
  const gameUrl='https://nikunekostudio.github.io/games/hashire-oniku/',monthlyApi='https://nikuneko-monthly-scores-api.nikunekokikaku.workers.dev',projectId='ac233dc3-38ac-474f-8b1f-06808458696c',leaderboardId='34dc470e-8c6e-43b6-8bb1-519c4429849e',sessionId=crypto.randomUUID();
  let scene='title',last=0,muted=false,score=0,best=Number(localStorage.getItem('hashireOnikuBest')||0),speed=550,spawnDelay=2,spawnTimer=0,ammo=3,bonus=Number(localStorage.getItem('hashireOnikuShiitakeBonus')||0),objects=[],bullets=[],dust=[],deadTimer=0,fortune='',jumpBuffer=0,coyoteTime=0;
  const player={x:66,y:ground-82,w:110,h:82,vy:0,onFloor:true,frame:0,dead:false};
  const rand=(a,b)=>a+Math.random()*(b-a),randi=(a,b)=>Math.floor(rand(a,b+1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const play=(a,vol=1)=>{if(muted)return;a.volume=vol;a.currentTime=0;a.play().catch(()=>{})};
  const music=(a,vol=.3)=>{Object.values(audio).forEach(x=>{if(x!==a&&x.loop)x.pause()});if(!muted){a.volume=vol;a.play().catch(()=>{})}};
  const stopMusic=()=>{audio.stage.pause();audio.result.pause()};
  const fit=(im,x,y,w,h)=>{if(!im.complete||!im.naturalWidth)return;const s=Math.min(w/im.naturalWidth,h/im.naturalHeight);ctx.drawImage(im,x+(w-im.naturalWidth*s)/2,y+(h-im.naturalHeight*s)/2,im.naturalWidth*s,im.naturalHeight*s)};
  const trims={'oniku10.png':[208,382,827,600],'oniku11.png':[205,377,833,606],'oniku12.png':[202,378,838,606],'oniku13.png':[276,295,699,626],'oniku6.png':[170,259,917,746],'kabu.png':[4,8,113,120],'tori.png':[0,50,124,73],'shitake.png':[35,65,64,60],'uributa.png':[62,8,162,293]};
  const sprite=(name,x,y,w,h)=>{const im=img[name],b=trims[name];if(!im.complete||!im.naturalWidth)return;if(!b){fit(im,x,y,w,h);return}const s=Math.min(w/b[2],h/b[3]),dw=b[2]*s,dh=b[3]*s;ctx.drawImage(im,b[0],b[1],b[2],b[3],x+(w-dw)/2,y+h-dh,dw,dh)};
  const text=(s,x,y,size=28,align='left',color='#fff')=>{ctx.save();ctx.font=`700 ${size}px Arial, sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.lineWidth=Math.max(3,size/8);ctx.strokeStyle='#25201c';ctx.strokeText(s,x,y);ctx.fillStyle=color;ctx.fillText(s,x,y);ctx.restore()};
  const hit=(a,b,p=12)=>a.x+p<b.x+b.w-p&&a.x+a.w-p>b.x+p&&a.y+p<b.y+b.h-p&&a.y+a.h-p>b.y+p;
  function reset(){score=0;speed=550;spawnDelay=2;spawnTimer=0;ammo=3+bonus;objects=[];bullets=[];dust=[];deadTimer=0;jumpBuffer=0;coyoteTime=.09;Object.assign(player,{x:66,y:ground-82,vy:0,onFloor:true,frame:0,dead:false})}
  function hideResult(){resultPanel.hidden=true;scoreStatus.textContent='';scoreForm.querySelector('button').disabled=false}
  function start(){hideResult();reset();scene='play';music(audio.stage,.3)}
  function gameOver(){if(player.dead)return;player.dead=true;scene='dead';deadTimer=0;audio.stage.pause();play(audio.dead,.8);best=Math.max(best,Math.floor(score));localStorage.setItem('hashireOnikuBest',best)}
  function showResult(){scene='result';music(audio.result,.3);const final=Math.floor(score);resultScore.textContent=`SCORE  ${final.toLocaleString('ja-JP')}`;resultBest.textContent=`BEST  ${best.toLocaleString('ja-JP')}`;document.querySelector('#share-x').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(`『走れ！おにく！』で${final.toLocaleString('ja-JP')}点！\nあなたは何点取れる？\n#走れおにく #にくねこスタジオ`)+'&url='+encodeURIComponent(gameUrl);resultPanel.hidden=false}
  function title(){hideResult();scene='title';stopMusic();fortune=''}
  function jump(){if(scene==='title'||scene==='result'){start();return}if(scene==='play')jumpBuffer=.14}
  function shoot(){if(scene!=='play'||ammo<1)return;ammo--;bullets.push({x:player.x+88,y:player.y+2,w:86,h:78});play(audio.hit,.35)}
  function spawnOne(){const type=randi(0,6),x=W+rand(75,125);if(type===0)objects.push({type:'kabu',x,y:ground-122,w:122,h:122});if(type===1||type===5){objects.push({type:'island',x,y:315,w:170,h:88});objects.push({type:type===1?'stock':'mushroom',x:x+45,y:type===1?245:220,w:type===1?86:100,h:type===1?60:92})}if(type===2||type===3){const count=randi(1,Math.min(3,1+Math.round(clamp(score/3000,0,4))));for(let i=0;i<count;i++)objects.push({type:'kabu',x:x+i*94,y:ground-122,w:122,h:122})}if(type===4)objects.push({type:'tori',x,y:240,w:140,h:90});if(type===6)objects.push({type:'uributa',x,y:ground-190,w:190,h:190})}
  function updatePlay(dt){
    score+=Math.round(dt*100);speed=Math.min(2000,speed+dt*8);spawnDelay=Math.max(.7,spawnDelay-dt/30);spawnTimer+=dt;if(spawnTimer>=spawnDelay){spawnTimer=0;spawnOne()}
    jumpBuffer=Math.max(0,jumpBuffer-dt);coyoteTime=player.onFloor ? .09 : Math.max(0,coyoteTime-dt);const prevBottom=player.y+player.h;player.vy+=2300*dt;player.y+=player.vy*dt;player.onFloor=false;let floor=ground-player.h;
    for(const o of objects)if(o.type==='island'&&player.vy>=0&&player.x+player.w*.65>o.x&&player.x+player.w*.25<o.x+o.w&&prevBottom<=o.y&&player.y+player.h>=o.y)floor=Math.min(floor,o.y-player.h);
    if(player.y>=floor){player.y=floor;player.vy=0;player.onFloor=true;coyoteTime=.09}if(jumpBuffer>0&&(player.onFloor||coyoteTime>0)){player.vy=-940;player.onFloor=false;jumpBuffer=0;coyoteTime=0;play(audio.jump,.8)}player.frame+=dt*9;objects.forEach(o=>o.x-=speed*dt);bullets.forEach(b=>b.x+=1250*dt);objects=objects.filter(o=>o.x>-220);bullets=bullets.filter(b=>b.x<W+80);
    if(player.onFloor&&Math.random()<dt*13)dust.push({x:player.x+25,y:ground-5,life:.45,r:rand(2,7)});dust.forEach(d=>{d.x-=speed*.3*dt;d.life-=dt});dust=dust.filter(d=>d.life>0);
    for(const o of [...objects]){if((o.type==='stock'||o.type==='mushroom')&&hit(player,o,12)){if(o.type==='stock')score+=1000;else ammo++;play(audio.coin,.8);objects.splice(objects.indexOf(o),1);continue}if(['kabu','tori','uributa'].includes(o.type)&&hit(player,o,12))gameOver();for(const b of bullets)if(['kabu','tori','uributa'].includes(o.type)&&hit(b,o,2)){objects.splice(objects.indexOf(o),1);score+=100;play(audio.hit,.5);break}}
    const levels=[5000,10000,15000,20000,25000,30000,50000],newBonus=levels.filter(v=>score>=v).length;if(newBonus>bonus){bonus=newBonus;localStorage.setItem('hashireOnikuShiitakeBonus',bonus)}
  }
  function update(dt){if(scene==='play')updatePlay(dt);if(scene==='dead'){deadTimer+=dt;if(deadTimer>1.15)showResult()}}
  function background(scroll=0){ctx.drawImage(img['sky.png'],0,0,W,ground);for(let x=-(scroll%64);x<W;x+=64){ctx.drawImage(img['desert-top.png'],x,ground,64,16);ctx.drawImage(img['desert-tile.png'],x,ground+16,64,64)}}
  function drawPlayer(dead=false){const frames=['oniku10.png','oniku11.png','oniku12.png'],name=dead?'oniku6.png':(!player.onFloor?'oniku13.png':frames[Math.floor(player.frame)%3]);sprite(name,player.x,player.y,player.w,player.h)}
  function drawTitle(){background();fit(img['himeniku.png'],576,42,128,128);text('走れ！おにく！',250,125,58,'center','#e84242');text('Run, Oniku!',250,190,30,'center','#ffd34e');text(`HIGH SCORE  ${best}`,720,80,22,'center','#27211b');ctx.fillStyle='#8f602e';ctx.fillRect(608,145,192,22);fit(img['shitake.png'],736,385,74,100);text('きょうの運勢',773,350,18,'center','#fff');fit(img['oniku10.png'],350,300,250,210);text('おにくを押してスタート',480,455,25,'center','#fff');if(fortune)text(fortune,772,430,24,'center','#ffd34e')}
  const art={kabu:'kabu.png',stock:'stock.png',tori:'tori.png',mushroom:'shitake.png',island:'island.png',uributa:'uributa.png'};
  function drawPlay(){background(score*5);text(`目標 Score:30000   Score  ${Math.floor(score)}`,21,28,23,'left','#27211b');sprite('shitake.png',18,52,68,64);text(`× ${ammo}`,88,84,25,'left','#27211b');dust.forEach(d=>{ctx.globalAlpha=d.life*2;ctx.fillStyle='#9c6f35';ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;for(const o of objects)sprite(art[o.type],o.x,o.y,o.w,o.h);for(const b of bullets)sprite('shitake.png',b.x,b.y,b.w,b.h);drawPlayer(false)}
  function drawDead(){drawPlay();drawPlayer(true)}
  function drawResult(){background();const cast=[['oniku10.png',32,380,160]];if(score>10000)cast.push(['shitake3.png',672,0,128]);if(score>15000)cast.push(['kani.png',0,210,150]);if(score>20000)cast.push(['miia.png',288,378,155]);if(score>25000)cast.push(['zarigani.png',810,230,125]);if(score>30000)cast.push(['neko.png',760,20,190]);if(score>50000)cast.push(['shika.png',700,260,260]);if(score>100000)cast.push(['sumomo.png',210,12,110]);if(score>300000)cast.push(['himeniku.png',30,95,130]);cast.forEach(([n,x,y,s])=>fit(img[n],x,y,s,s))}
  function draw(){ctx.clearRect(0,0,W,H);if(scene==='title')drawTitle();if(scene==='play')drawPlay();if(scene==='dead')drawDead();if(scene==='result')drawResult()}
  function frame(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}
  function pointer(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(scene==='title'){if(x>690&&y>325){const fortunes=['大吉','中吉','小吉','吉','末吉','凶','大凶'];fortune=fortunes[randi(0,6)]}else if(x>330&&x<610&&y>245&&y<465)start();return}if(scene==='result'){if(y>290&&y<385&&x>300&&x<510)start();else if(y>290&&y<385&&x>500&&x<720)title();return}if(scene==='play')jump()}
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();pointer(e)});document.querySelector('#jump').addEventListener('pointerdown',e=>{e.preventDefault();jump()});document.querySelector('#shoot').addEventListener('pointerdown',e=>{e.preventDefault();shoot()});addEventListener('keydown',e=>{if(e.target.matches?.('input,button,a'))return;if(['Space','ArrowUp','ArrowDown','Enter'].includes(e.code))e.preventDefault();if((e.code==='Space'||e.code==='ArrowUp'||e.code==='Enter')&&!e.repeat)jump();if(e.code==='ArrowDown'&&!e.repeat)shoot();if(e.code==='Escape')title()});
  document.querySelector('#retry').addEventListener('click',start);document.querySelector('#back-title').addEventListener('click',title);
  scoreForm.addEventListener('submit',async e=>{e.preventDefault();const name=playerName.value.trim().replace(/\s+/g,'_').slice(0,20),final=Math.floor(score),button=scoreForm.querySelector('button');if(!name)return;button.disabled=true;scoreStatus.textContent='登録中…';try{let clientPlayerId=localStorage.getItem('hashireOnikuPlayerId');if(!clientPlayerId){clientPlayerId=crypto.randomUUID();localStorage.setItem('hashireOnikuPlayerId',clientPlayerId)}const body=JSON.stringify({score:final,sessionId,clientPlayerId,location:gameUrl,playerName:name});const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)),digest=btoa(String.fromCharCode(...new Uint8Array(bytes)));const [allTime,monthly]=await Promise.all([fetch(`https://api.gdevelop.io/play/game/${projectId}/leaderboard/${leaderboardId}/entry`,{method:'POST',headers:{'Content-Type':'application/json',Digest:digest},body}),fetch(monthlyApi+'/scores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:'hashire-oniku',name,score:final,playerId:clientPlayerId})})]);if(!allTime.ok||!monthly.ok)throw new Error('Save failed');scoreStatus.textContent='走れ！の総合・月間ランキングに登録しました！'}catch{scoreStatus.textContent='登録できませんでした。時間をおいて再度お試しください。';button.disabled=false}});
  document.querySelector('#sound').addEventListener('click',e=>{muted=!muted;e.currentTarget.textContent=muted?'♪ OFF':'♪ ON';e.currentTarget.setAttribute('aria-pressed',String(muted));Object.values(audio).forEach(a=>a.muted=muted);if(!muted&&scene==='play')music(audio.stage,.3);if(!muted&&scene==='result')music(audio.result,.3)});requestAnimationFrame(frame);
})();
